### ISSUE TITLE
How can I find the initial pose ?

### ISSUE THREAD

**Issue by arjunskumar** [HViktorTsoi/FAST_LIO_LOCALIZATION#11]
Hi, can anyone tell how to find the initial pose of my robot ?

**Comment by HViktorTsoi** [comment]
Hi, the `initial pose` is a manually-specified rough position / pose of the robot relative to the `map`,  it is pretty much the same as setting initial pose in ros navigation stack, please refer to this video https://www.youtube.com/watch?v=7qiew0powLc
