### ISSUE TITLE
it is hard to give a initial pose

### ISSUE THREAD

**Issue by pjs9115916** [HViktorTsoi/FAST_LIO_LOCALIZATION#21]
I use my data from velodyne 16p. actually I think I gaved a precise initial pose (just like the picture as follow),but the score is only about 0.5. and it always WARN:Waiting for initial pose.....      so whether the initial pose is right or not?

`[INFO] [1673945350.131224]: Global localization by scan-to-map matching......
[INFO] [1673945350.357125]: Time: 0.222168922424
[INFO] [1673945350.358185]: 
[WARN] [1673945350.359048]: Not match!!!!
[WARN] [1673945350.360114]: [[ 0.9983036  -0.02998865 -0.04990596  8.62335004]
 [ 0.03053204  0.99948213  0.01016162  0.67196513]
 [ 0.04957538 -0.01166811  0.99870223 -0.17253242]
 [ 0.          0.          0.          1.        ]]
[WARN] [1673945350.361129]: fitness score:0.529914529915
[WARN] [1673945350.361972]: Waiting for initial pose....
`
![Screenshot from 2023-01-17 16-57-57](https://user-images.githubusercontent.com/10228710/212853987-977816c8-7b61-4d71-8ff7-eab7381b9452.png)

**Comment by JokerJohn** [comment]
i think you can save the first point cloud frame and manually align it to the global map using ColudCompare.

**Comment by pjs9115916** [comment]
Actually  , I already solved it . In my case I should modified the FOV to 360
